# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e57bb457337ea30ffd1c04ad8aa8a4cb"
name = "app2"
handle = "app2-274"
application_url = "https://bristol-operate-first-pittsburgh.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "fffff12345test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_returns"

[auth]
redirect_urls = [
  "https://bristol-operate-first-pittsburgh.trycloudflare.com/auth/callback",
  "https://bristol-operate-first-pittsburgh.trycloudflare.com/auth/shopify/callback",
  "https://bristol-operate-first-pittsburgh.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
